# ──────────────────────────────────────────────────────────────
# config/agents.yaml  – Gemini via OpenAI-compatible Chat Completions
# works with autogen-core/agentchat/ext == 0.5.7 + autogen-ext[openai]
# ──────────────────────────────────────────────────────────────

# ─── USER PROXY ────────────────────────────────────────────────
- name: user_proxy
  provider: autogen_agentchat.agents.UserProxyAgent
  component_type: agent
  config:
    name: user_proxy
    human_input_mode: ALWAYS
    code_execution_config: false

# ─── QUERY-REFINER (uses Gemini) ───────────────────────────────
- name: query_refiner
  provider: autogen_agentchat.agents.AssistantAgent
  component_type: agent
  config:
    name: query_refiner
    description: Clarifies user queries and expands them with synonyms/MeSH terms.
    system_message: |
      You are the Query Refiner Agent. …
    reflect_on_tool_use: false
    tool_call_summary_format: "{result}"
        # anchor lives HERE, not as a separate list item
    model_client: &gemini_openai_client
      provider: autogen_ext.models.openai.OpenAIChatCompletionClient
      component_type: model
      config:
        model:    "${GEMINI_MODEL:-gemini-2.5-flash-preview-04-17}"
        base_url: "${OPENAI_API_BASE}"
        api_key:  "${OPENAI_API_KEY}"
        temperature: 0.2
        model_info:
          structured_output: false      # ← new required field
          vision: false
          json_output: true
          function_calling: true
          family: "GEMINI_2_5_FLASH"

# ─── TRIAGE / RANKER (unchanged; no LLM) ─────────────
- name: triage
  provider: tools.triage.TriageAgent
  component_type: agent
  config:
    name: triage
    system_message: |
      You are the Triage Agent. Your responsibility is to perform a first-pass
      relevance assessment of search results based on title and abstract, and
      filter by journal quality, OA status, and age-normalised citation count.
      You will also handle full-text retrieval and a deeper triage using key
      passages.

- name: ranker
  provider: tools.ranking.RankerAgent
  component_type: agent
  config:
    name: ranker
    system_message: |
      You are the Ranker Agent. Your task is to combine various metrics,
      including LLM relevance scores, z-scored citation rates, and journal SJR
      percentiles, into a final ranked list of literature.


# ─── SUMMARISER (also Gemini) ─────────────────────────────────
- name: summariser
  provider: autogen_agentchat.agents.AssistantAgent
  component_type: agent
  config:
    name: summariser
    description: Creates a structured Markdown summary of ranked papers.
    system_message: |
      You are the Summariser Agent. …
    reflect_on_tool_use: false
    tool_call_summary_format: "{result}"
    model_client: *gemini_openai_client

# ─── EXPORTER (unchanged) ─────────────────────────────────────
- name: exporter
  provider: tools.export.ExporterAgent
  component_type: agent
  config:
    name: exporter
    system_message: |
      You are the Exporter Agent. Your responsibilities include building RIS
      files, ensuring all cited PDFs are fetched and saved correctly, writing
      the final Markdown report to disk, and creating a convenience ZIP archive
      of the outputs.

- name: search_literature
  provider: tools.search.LiteratureSearchTool
  component_type: tool
  config: {}
