version: '0.1'
weights:
  relevance: 0.5
  journal_quality: 0.2
  citation_zscore: 0.3
caps:
  max_results_per_api: 250
  max_ranked_papers: 100
  max_summary_tokens: 2048
triage:
  sjr_percentile_threshold: 50  # Accept journals in the top 50% (Q1 and Q2)
  min_age_normalized_citations: 1.0  # Require at least 1 citation per year since publication
  open_access_statuses:
    - gold
    - hybrid
    - green
resolve_content_timeout: 15 # seconds
resolve_max_retries: 3
resolve_retry_backoff_factor: 0.5 # seconds
resolve_retry_status_forcelist: [500, 502, 503, 504] # HTTP status codes to retry on
resolve_per_domain_concurrency: 2 # Max concurrent requests per domain

proxy_settings:
  enabled: false # Set to true to enable proxies
  proxies: # List of proxy URLs, e.g., ["http://user:pass@host:port"]
    # - "http://your_proxy_url_1"
    # - "http://your_proxy_url_2"
