# Configuration for literature search agent

# API Keys and Endpoints (can be overridden by .env variables)
# Example:
# api_keys:
#   pubmed: YOUR_PUBMED_KEY_HERE
#   semantic_scholar: YOUR_S2_KEY_HERE

# Search settings
search_settings:
  default_max_results_per_source: 100
  default_publication_types: # Default if --pub-types CLI flag is not used
    - "research"
    - "review"
  # Add other search-related defaults here if needed

# Mappings for publication types from user input (CLI/default) to API-specific terms
publication_type_mappings:
  research: # User input string "research"
    pubmed: "Journal Article[Publication Type]" # Value for PubMed 'term' filter
    europepmc: "PUB_TYPE:\"journal-article\""  # Value for EuropePMC query
    semanticscholar: "JournalArticle"          # Value for Semantic Scholar 'publication_types' parameter
    crossref: "journal-article"                # Value for CrossRef 'type' filter
    openalex: "journal-article"                # Value for OpenAlex 'type' filter (or 'work_type' if that's confirmed)
  review: # User input string "review"
    pubmed: "Review[Publication Type]"
    europepmc: "PUB_TYPE:\"review\""
    semanticscholar: "Review"
    crossref: "review-article"
    openalex: "review-article"

# Triage Agent Settings (example)
triage_settings:
  relevance_threshold: 3 # Example: minimum score to keep an article
  # other triage parameters...

# Ranking Agent Settings (example)
ranking_settings:
  # parameters for ranking...
  weights:
    year: 0.2
    citation_count: 0.5
    # other ranking criteria...

# LLM Model configurations (used by agents that call LLMs)
# These are illustrative; actual structure depends on how agents load model configs.
# model_configs:
#   query_refiner_model:
#     provider: "openai" # or "azure", "anthropic", etc.
#     model_name: "gpt-3.5-turbo"
#     # other model parameters like temperature, max_tokens
#   triage_model:
#     provider: "openai"
#     model_name: "gpt-4"

# Other application-wide settings
# Example:
# logging_level: "INFO"
